### ISSUE TITLE
problema con requirements en ubuntu 20

### ISSUE THREAD

**Issue by gentooza** [Mercado-Social-de-Madrid/gestionMES#80]
Hola!

Otro fallo que he tenido poniendo en marcha la aplicación es con los paquetes definidos en requirements.txt

Con las librerías que instala ubuntu 20, he tenido que **quitarle la limitación de versión a mysqlclient**.

También he tenido problemas con **six**, me vale mejor la **1.14**, o simplemente quitarle el limitador de versión.

Soy bastante novato en django, así que si no es una solución válida os agradecería un porque :-D es que mirando por internet veo que tiran de librerías del sistema y no había otra opción.

un saludo!

**Comment by jjoseba** [comment]
Hola!
La verdad es que lo suyo sería directamente quitar la mención a `mysqlclient` del todo, ya que luego a nivel de settings se puede configurar con el cliente que se quiera, y no hay nada a nivel de ORM que requiera un gestor de base de datos concreto... gracias por la sugerencia! en estos días le doy una vuelta a todos los requisitos y actualizo a versiones más recientes que sean compatibles con lo actual

**Comment by gentooza** [comment]
ammm, claro!

un saludo y mucho ánimo!
